
spring:
  datasource:
    url: jdbc:mysql://localhost/db_la_promesa?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Santiago
    username: root
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto:  create

name: la-promesa


server:
  port: 8080
  servlet:
    context-path: /api/${name}/v1/
